### ISSUE TITLE
No shares accepted (or even sent?) starting with release v6.21.3-mo5

### ISSUE THREAD

**Issue by Fjodor42** [MoneroOcean/xmrig#131] opened 2024-05-29 00:40 UTC
**Describe the bug**
A number of releases where made recently, but starting with v6.21.3-mo5, I get no messages of "accepted", and node doesn't get displayed at the pool dashboard.

In effect, even thought he code compiles, and `xmrig` seems to run, no shares seem to be accepted, possibly because they are never sent.

Suspicion is that the benchmark changes were somehow too invasive, somehow managing to convince that after benchmarks, from which I assume that shares should not not be sent, no real shares are ever sent either.

**To Reproduce**
Compile and run release v6.21.3-mo5 or any of the ones that followed.

**Expected behavior**
Running `xmrig` would benchmark, the proceed to find and send shares.

**Required data**
 - XMRig version
  - Any, starting with v6.21.3-mo5
 - Miner log for v6.21.3-mo5
   - ![image](https://github.com/MoneroOcean/xmrig/assets/1410995/a1697ab5-2fdd-4440-9d86-cd8fac9d1be5)
 - Miner log for v6.21.3-mo4
   - ![image](https://github.com/MoneroOcean/xmrig/assets/1410995/79651cc4-0ba4-408d-9874-cefbe0efe703)
 - Config file irrelevant - this happens across CPU or CUDA runs on all my machines with config that worked before v6.21.3-mo5
 - OS: Linux

**Comment by Spudz76** [comment] 2024-05-29 09:37
Seems like it's because this one line was removed from `MoBenchmark::finish`

Without the listener restored to normal, it can't validate or submit results.

```
diff --git a/src/core/MoBenchmark.cpp b/src/core/MoBenchmark.cpp
index ddfb03eca..fba92449c 100644
--- a/src/core/MoBenchmark.cpp
+++ b/src/core/MoBenchmark.cpp
@@ -56,6 +56,7 @@ void MoBenchmark::finish() {
     LOG_INFO("%s " BRIGHT_BLACK_BG(CYAN_BOLD_S " ALGO PERFORMANCE CALIBRATION COMPLETE "), Tags::benchmark());
     m_controller->miner()->pause(); // do not compute anything before job from the pool
     JobResults::stop();
+    JobResults::setListener(m_controller->network(), m_controller->config()->cpu().isHwAES());
     m_controller->start();
 }

```

**Comment by Spudz76** [comment] 2024-05-29 09:48
Confirmed that fixes it after running for a bit.

**Comment by realsetvin** [comment] 2024-05-29 12:39
> Confirmed that fixes it after running for a bit.

was this fixed in the new version released?

**Comment by serisman** [comment] 2024-05-29 15:12
> Seems like it's because this one line was removed from `MoBenchmark::finish`

Thanks for the patch.  I can confirm it seems to fix the issue of shares not being accepted (on mo8) on my test system as well.

**Closed** 2024-05-29 15:45 UTC
